# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CHyperparameterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoAboutCWindow(object):
    def setupUi(self, InfoAboutCWindow):
        InfoAboutCWindow.setObjectName("InfoAboutCWindow")
        InfoAboutCWindow.resize(850, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Facultate/Licenta/dot-crossed_icon-icons.com_68558.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        InfoAboutCWindow.setWindowIcon(icon)
        with open('CHyperparameterWindow.qss', 'r') as f:
            style = f.read()
            InfoAboutCWindow.setStyleSheet(style)

        self.infoText = "C is the penalty parameter, which represents misclassification or error\n" \
                        "term. The misclassification or error term tells the SVM optimization how\n" \
                        "much error is bearable. This is how you can control the trade-off\n" \
                        "between decision boundary and misclassification term. A smaller value\n" \
                        "of C creates a big-margin hyperplane and a larger value of C creates a\n" \
                        "small-margin hyperplane."
        self.recommendedValuesText = "By default C will be 1.0, but you can try lower values for a bigger\n" \
                                     "margin such as 0.2 or even 0.01. Try using a very high value such as\n" \
                                     "20 in order to get a more interesting result in terms of visuals."

        self.centralwidget = QtWidgets.QWidget(InfoAboutCWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleFrame = QtWidgets.QFrame(self.mainFrame)
        self.titleFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout.addWidget(self.titleFrame)
        self.scrollArea = QtWidgets.QScrollArea(self.mainFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 841, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.subtitleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subtitleLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout_3.addWidget(self.subtitleLabel)
        self.infoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.infoLabel.setText("")
        self.infoLabel.setTextFormat(QtCore.Qt.PlainText)
        self.infoLabel.setScaledContents(False)
        self.infoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.infoLabel.setWordWrap(False)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_3.addWidget(self.infoLabel)
        self.recommendedValuesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.recommendedValuesLabel.setText("")
        self.recommendedValuesLabel.setObjectName("recommendedValuesLabel")
        self.verticalLayout_3.addWidget(self.recommendedValuesLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.mainFrame)
        InfoAboutCWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InfoAboutCWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoAboutCWindow)

    def retranslateUi(self, InfoAboutCWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoAboutCWindow.setWindowTitle(_translate("InfoAboutCWindow", "C Hyperparameter"))
        self.mainFrame.setAccessibleName(_translate("InfoAboutCWindow", "mainFrame"))
        self.titleFrame.setAccessibleName(_translate("InfoAboutCWindow", "titleFrame"))
        self.titleLabel.setAccessibleName(_translate("InfoAboutCWindow", "titleLabel"))
        self.titleLabel.setText(_translate("InfoAboutCWindow", "SVM Visualizer"))
        self.subtitleLabel.setAccessibleName(_translate("InfoAboutCWindow", "subtitleLabel"))
        self.subtitleLabel.setText(_translate("InfoAboutCWindow", "About the C hyperparameter"))
        self.infoLabel.setAccessibleName(_translate("InfoAboutCWindow", "infoLabel"))
        self.infoLabel.setText(_translate("InfoAboutCWindow", self.infoText))
        self.recommendedValuesLabel.setAccessibleName(_translate("InfoAboutCWindow", "recommendedValuesLabel"))
        self.recommendedValuesLabel.setText(_translate("InfoAboutCWindow", self.recommendedValuesText))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InfoAboutCWindow = QtWidgets.QMainWindow()
    ui = Ui_InfoAboutCWindow()
    ui.setupUi(InfoAboutCWindow)
    InfoAboutCWindow.show()
    sys.exit(app.exec_())
