# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DegreeParameterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoAboutDegreeWindow(object):
    def setupUi(self, infoAboutDegreeWindow):
        infoAboutDegreeWindow.setObjectName("infoAboutDegreeWindow")
        infoAboutDegreeWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Facultate/Licenta/dot-crossed_icon-icons.com_68558.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        infoAboutDegreeWindow.setWindowIcon(icon)
        with open('DegreeParameterWindow.qss', 'r') as f:
            style = f.read()
            infoAboutDegreeWindow.setStyleSheet(style)

        self.infoText = "This parameter is used inside the polynomial kernel function.\n" \
                        "This kernel looks not onlu at the given features of input\n" \
                        "samples to determine their similarity, but also combinations\n" \
                        "of these. The degree represents the power of the polynomial\n" \
                        "expression that defines this kernel.\n" \
                        "\nPolynomial kernel equation: K(x,y)=(γxy+C)^d"
        self.recommendedValuesText = "By default the degree will be 2, but you can try higher values\n" \
                                     "for a more fitted model. However, don't try using values higher\n" \
                                     "than 5 or 6, as everyhing about these highlly raises the complexity\n" \
                                     "of the calculus and that can make the program take too long to\n" \
                                     "responde. Everything between 2 and 6 should provide accurate\n" \
                                     "results in a short period of time (5-6 seonds)."

        self.centralwidget = QtWidgets.QWidget(infoAboutDegreeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleFrame = QtWidgets.QFrame(self.mainFrame)
        self.titleFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout.addWidget(self.titleFrame)
        self.scrollArea = QtWidgets.QScrollArea(self.mainFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 756, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.subtitleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subtitleLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout_3.addWidget(self.subtitleLabel)
        self.infoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_3.addWidget(self.infoLabel)
        self.recommendedValuesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.recommendedValuesLabel.setObjectName("recommendedValuesLabel")
        self.verticalLayout_3.addWidget(self.recommendedValuesLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.mainFrame)
        infoAboutDegreeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(infoAboutDegreeWindow)
        QtCore.QMetaObject.connectSlotsByName(infoAboutDegreeWindow)

    def retranslateUi(self, infoAboutDegreeWindow):
        _translate = QtCore.QCoreApplication.translate
        infoAboutDegreeWindow.setWindowTitle(_translate("infoAboutDegreeWindow", "Degree Parameter"))
        self.mainFrame.setAccessibleName(_translate("infoAboutDegreeWindow", "mainFrame"))
        self.titleFrame.setAccessibleName(_translate("infoAboutDegreeWindow", "titleFrame"))
        self.titleLabel.setAccessibleName(_translate("infoAboutDegreeWindow", "titleLabel"))
        self.titleLabel.setText(_translate("infoAboutDegreeWindow", "SVM Visualizer"))
        self.subtitleLabel.setAccessibleName(_translate("infoAboutDegreeWindow", "subtitleLabel"))
        self.subtitleLabel.setText(_translate("infoAboutDegreeWindow", "About the degree parameter"))
        self.infoLabel.setAccessibleName(_translate("infoAboutDegreeWindow", "infoLabel"))
        self.infoLabel.setText(_translate("infoAboutDegreeWindow",self.infoText))
        self.recommendedValuesLabel.setAccessibleName(_translate("infoAboutDegreeWindow", "recommendedValuesLabel"))
        self.recommendedValuesLabel.setText(_translate("infoAboutDegreeWindow", self.recommendedValuesText))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infoAboutDegreeWindow = QtWidgets.QMainWindow()
    ui = Ui_infoAboutDegreeWindow()
    ui.setupUi(infoAboutDegreeWindow)
    infoAboutDegreeWindow.show()
    sys.exit(app.exec_())
