# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GammaHyperparameterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoAboutGammaWindow(object):
    def setupUi(self, infoAboutGammaWindow):
        infoAboutGammaWindow.setObjectName("infoAboutGammaWindow")
        infoAboutGammaWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Facultate/Licenta/dot-crossed_icon-icons.com_68558.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        infoAboutGammaWindow.setWindowIcon(icon)
        with open('GammaHyperparameterWindow.qss', 'r') as f:
            style = f.read()
            infoAboutGammaWindow.setStyleSheet(style)

        self.infoText = "A lower value of Gamma will loosely fit the training dataset,\n" \
                        "whereas a higher value of gamma will exactly fit the training\n" \
                        "dataset, which causes over-fitting. In other words, you can say\n" \
                        "a low value of gamma considers only nearby points in calculating\n" \
                        "the separation line, while the a value of gamma considers all\n" \
                        "the data points in the calculation of the separation line."
        self.recommendedValuesText = "By default Gamma will be 0.8, but you can try lower values\n" \
                                     "for a looser fitting such as 0.4 or 0.6. Try using a very high\n" \
                                     "value such as 50 or even 100 in order to get a more interesting\n" \
                                     "result in terms of visuals. From a certain value there will be\n" \
                                     "almost no visual difference. (Ex: 0.00001 or 1000)"

        self.centralwidget = QtWidgets.QWidget(infoAboutGammaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleFrame = QtWidgets.QFrame(self.mainFrame)
        self.titleFrame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout.addWidget(self.titleFrame)
        self.scrollArea = QtWidgets.QScrollArea(self.mainFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 756, 459))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.subtitleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subtitleLabel.setMaximumSize(QtCore.QSize(16777215, 80))
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout_2.addWidget(self.subtitleLabel)
        self.infoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_2.addWidget(self.infoLabel)
        self.recommendedValuesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.recommendedValuesLabel.setObjectName("recommendedValuesLabel")
        self.verticalLayout_2.addWidget(self.recommendedValuesLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.mainFrame)
        infoAboutGammaWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(infoAboutGammaWindow)
        QtCore.QMetaObject.connectSlotsByName(infoAboutGammaWindow)

    def retranslateUi(self, infoAboutGammaWindow):
        _translate = QtCore.QCoreApplication.translate
        infoAboutGammaWindow.setWindowTitle(_translate("infoAboutGammaWindow", "Gamma Hyperparameter"))
        self.mainFrame.setAccessibleName(_translate("infoAboutGammaWindow", "mainFrame"))
        self.titleFrame.setAccessibleName(_translate("infoAboutGammaWindow", "titleFrame"))
        self.titleLabel.setAccessibleName(_translate("infoAboutGammaWindow", "titleLabel"))
        self.titleLabel.setText(_translate("infoAboutGammaWindow", "SVM Visualizer"))
        self.subtitleLabel.setAccessibleName(_translate("infoAboutGammaWindow", "subtitleLabel"))
        self.subtitleLabel.setText(_translate("infoAboutGammaWindow", "About the Gamma hyperparameter"))
        self.infoLabel.setAccessibleName(_translate("infoAboutGammaWindow", "infoLabel"))
        self.infoLabel.setText(_translate("infoAboutGammaWindow", self.infoText))
        self.recommendedValuesLabel.setAccessibleName(_translate("infoAboutGammaWindow", "recommendedValuesLabel"))
        self.recommendedValuesLabel.setText(_translate("infoAboutGammaWindow", self.recommendedValuesText))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    infoAboutGammaWindow = QtWidgets.QMainWindow()
    ui = Ui_infoAboutGammaWindow()
    ui.setupUi(infoAboutGammaWindow)
    infoAboutGammaWindow.show()
    sys.exit(app.exec_())
